In [ ]:
hdfs dfs -put /home/vagrant/bigdata-crimes-airbnb-project-dir/dim_date.csv /user/vagrant/bigdata/dimensions/dim_date.csv
hdfs dfs -put /home/vagrant/bigdata-crimes-airbnb-project-dir/dim_host_response_time.csv /user/vagrant/bigdata/dimensions/dim_host_response_time.csv
hdfs dfs -put /home/vagrant/bigdata-crimes-airbnb-project-dir/dim_room_type.csv /user/vagrant/bigdata/dimensions/dim_room_type.csv
hdfs dfs -put /home/vagrant/bigdata-crimes-airbnb-project-dir/dim_LAW_CAT_CD.csv /user/vagrant/bigdata/dimensions/dim_LAW_CAT_CD.csv
hdfs dfs -put /home/vagrant/bigdata-crimes-airbnb-project-dir/dim_JURISDICTION_CODE.csv /user/vagrant/bigdata/dimensions/dim_JURISDICTION_CODE.csv
hdfs dfs -put /home/vagrant/bigdata-crimes-airbnb-project-dir/dim_ARREST_BORO.csv /user/vagrant/bigdata/dimensions/dim_ARREST_BORO.csv
hdfs dfs -put /home/vagrant/bigdata-crimes-airbnb-project-dir/dim_age_group.csv /user/vagrant/bigdata/dimensions/dim_age_group.csv

SELECT
  arrest_key,
  arrest_date,
  pd_cd,
  NULLIF(TRIM(pd_desc), '')           AS pd_desc,
  ky_cd,
  NULLIF(TRIM(ofns_desc), '')         AS ky_desc,
  law_cat_cd,
  arrest_boro,
  arrest_precinct,
  jurisdiction_code,
  NULLIF(TRIM(age_group), '')         AS age_group,
  NULLIF(TRIM(perp_sex), '')          AS perp_sex,
  latitude,
  longitude
FROM FLOWFILE
WHERE
  NULLIF(TRIM(pd_desc), '') IS NOT NULL 
  AND CAST(latitude AS DOUBLE) <> 0 
  AND CAST(longitude AS DOUBLE) <> 0
LIMIT 200

https://data.cityofnewyork.us/resource/uip8-fykc.csv?$limit=50000&$offset=0
https://data.cityofnewyork.us/resource/uip8-fykc.csv?$limit=50000&$offset=50000
https://data.cityofnewyork.us/resource/uip8-fykc.csv?$limit=50000&$offset=100000
https://data.cityofnewyork.us/resource/uip8-fykc.csv?$limit=50000&$offset=150000
https://data.cityofnewyork.us/resource/uip8-fykc.csv?$limit=50000&$offset=200000

5.131670194948623

In [3]:
import numpy as np
import pandas as pd

## Listings

In [2]:
# load C:\Users\jancw\Desktop\Studia\Sem 7\BigData\Projekt\data\listings_london_14092025.csv
df_listings = pd.read_csv(r"C:\Users\jancw\Desktop\Studia\Sem 7\BigData\Projekt\data\listings_london_14092025.csv")

In [17]:
df_listings.head(20)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,13913,https://www.airbnb.com/rooms/13913,20250914034649,2025-09-16,city scrape,Holiday London DB Room Let-on going,My bright double bedroom with a large window h...,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,54730,...,4.87,4.78,4.78,NaN,f,2,1,1,0,0.30
1,15400,https://www.airbnb.com/rooms/15400,20250914034649,2025-09-16,city scrape,Bright Chelsea Apartment. Chelsea!,Lots of windows and light. St Luke's Gardens ...,It is Chelsea.,https://a0.muscache.com/pictures/428392/462d26...,60302,...,4.84,4.93,4.74,NaN,f,1,1,0,0,0.51
2,17402,https://www.airbnb.com/rooms/17402,20250914034649,2025-09-16,city scrape,Very Central Modern 3-Bed/2 Bath By Oxford St W1,"You'll have a great time in this beautiful, cl...","Fitzrovia is a very desirable trendy, arty and...",https://a0.muscache.com/pictures/39d5309d-fba7...,67564,...,4.72,4.89,4.61,NaN,f,2,2,0,0,0.32
3,24328,https://www.airbnb.com/rooms/24328,20250914034649,2025-09-18,previous scrape,Battersea live/work artist house,"Artist house by SW Battersea Park, bright high...","- Battersea is a quiet family area, easy acces...",https://a0.muscache.com/pictures/9194b40f-c627...,41759,...,4.93,4.60,4.65,NaN,f,1,1,0,0,0.53
4,36274,https://www.airbnb.com/rooms/36274,20250914034649,2025-09-15,city scrape,Bright 1 bedroom apt off brick lane in Shoreditch,*Update June '25- Pump Installed to improve wa...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,133271,...,4.46,4.85,4.54,NaN,t,2,2,0,0,0.09
5,36299,https://www.airbnb.com/rooms/36299,20250914034649,2025-09-15,city scrape,Kew Gardens 3BR house in cul-de-sac,3 Bed House with garden close to Thames river ...,"Residential family neighborhood, with both Eng...",https://a0.muscache.com/pictures/457052/6e819d...,155938,...,4.96,4.90,4.65,NaN,f,1,1,0,0,0.64
6,36660,https://www.airbnb.com/rooms/36660,20250914034649,2025-09-15,city scrape,You are GUARANTEED to love this,NaN,East Finchley is a friendly popular area of No...,https://a0.muscache.com/pictures/airflow/Hosti...,157884,...,4.96,4.77,4.86,NaN,t,2,0,2,0,4.00
7,38605,https://www.airbnb.com/rooms/38605,20250914034649,2025-09-15,city scrape,SUNNY ROOM PRIVATE BATHROOM PLUS BREAKFAST,Our guest room & bathroom overlooks the garden...,Shepherds Bush is one of London's truly divers...,https://a0.muscache.com/pictures/f489154c-1d54...,165579,...,4.89,4.53,4.77,NaN,f,3,2,1,0,2.14
8,38610,https://www.airbnb.com/rooms/38610,20250914034649,2025-09-16,city scrape,Short Term Home,"A typical Victorian Terraced London house, col...",Shepherds Bush itself is a prime real estate l...,https://a0.muscache.com/pictures/ace0185e-0f8a...,165579,...,4.98,4.79,4.69,NaN,f,3,2,1,0,0.26
9,38995,https://www.airbnb.com/rooms/38995,20250914034649,2025-09-14,city scrape,SPACIOUS ROOM IN CONTEMPORARY STYLE FLAT,Welcome to my place! I offer a large room in a...,Peckham itself is a vibrant and fashionable ar...,https://a0.muscache.com/pictures/1937395/94845...,167281,...,4.99,4.79,4.90,NaN,f,1,0,1,0,1.06
10,39387,https://www.airbnb.com/rooms/39387,20250914034649,2025-09-18,previous scrape,Stylish bedsit in Notting Hill ish flat.,Private lockable bedsit room available within ...,My place is convenient for all London attracti...,https://a0.muscache.com/pictures/beda1dab-9443...,168920,...,4.90,4.50,4.30,NaN,f,1,0,1,0,0.07
11,41445,https://www.airbnb.com/rooms/41445,20250914034649,2025-09-14,city scrape,2 Double bed apartment in quiet area North London,The apartment is on the ground floor (no stair...,Quite area popular with families,https://a0.muscache.com/pictures/7048777/dd495...,180838,...,4.56,4.64,4.16,NaN,f,1,1,0,0,0.15
12,41509,https://www.airbnb.com/rooms/41509,20250914034649,2025-09-18,previous scrape,Room in maisonette in chiswick,Double bed on 1st floor. 2 extra single beds i...,"great access to restaurants and cafes, and ea...",https://a0.muscache.com/pictures/bd97d842-122b...,181028,...,4.80,4.84,4.54,NaN,f,1,0,1,0,0.41
13,41712,https://www.airbnb.com/rooms/41712,20250914034649,2025-09-16,city scrape,"Room with a view, shared flat, central Bankside",A luminous room in a modern 2 bedroom flat loc...,"Location is great, 5 minute walk to Tate Moder...",https://a0.muscache.com/pictures/435470/00073a...,182322,...,4.85,4.86,4.60,NaN,f,2,1,1,0,0.77
14,41870,https://www.airbnb.com/rooms/41870,20250914034649,2025-09-18,previous scrape,Room in relaxed family house!,"Lovely friendly house, close to central line u...",People are friendly here and we are all neighb...,https://a0.muscache.com/pictures/miso/Hosting-...,182993,...,5.00,4.00,4.00,NaN,f,1,0,1,0,0.01
15,42010,https://www.airbnb.com/rooms/42010,20250914034649,2025-09-15,city scrape,You Will Save Money Here,Blenheim Lodge was built in 1878 when there we...,We have a unique cinema called the Phoenix whi...,https://a0.muscache.com/pictures/airflow/Hosti...,157884,...,4.95,4.75,4.88,NaN,t,2,0,2,0,3.50
16,42692,https://www.airbnb.com/rooms/42692,20250914034649,2025-09-18,previous scrape,Fabulous flat w garden and bkfst!,Holland Park/Notting Hill. Guests have access ...,The neighborhood of Holland Park borders Notti...,https://a0.muscache.com/pictures/239496/630e38...,186510,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
17,43129,https://www.airbnb.com/rooms/43129,20250914034649,2025-09-16,city scrape,Quiet Comfortable Room in Fulham,Munster Village is a colourful collection of s...,The area is called Munster village. It has a ...,https://a0.muscache.com/pictures/d90415e3-9d9f...,188138,...,4.81,4.66,4.73,NaN,f,3,0,3,0,1.79
18,43202,https://www.airbnb.com/rooms/43202,20250914034649,2025-09-18,previous scrape,Beautiful 1 bed apt in Queens Park,"A beautiful, light-filled, mid-century design ...",It's a really safe and friendly neighbourhood....,https://a0.muscache.com/pictures/miso/Hosting-...,188559,...,4.94,4.67,4.79,NaN,f,1,1,0,0,0.91
19,45163,https://www.airbnb.com/rooms/45163,20250914034649,2025-09-15,city scrape,Room with a garden,Nice room in house in the West Hampstead area ...,"West Hampstead is, to all intents and purposes...",https://a0.muscache.com/pictures/ec999674-6b16...,199530,...,5.00,5.00,4.00,NaN,f,1,0,1,0,0.02

In [32]:
saved_columns = ['id',
                 'last_scraped',
                 'name',
                 'description',
                 'neighborhood_overview',
                 'host_id',
                 'host_name',
                 'host_location',
                 'host_about',
                 'host_response_time',
                 'host_response_rate',
                 'host_acceptance_rate',
                 'host_is_superhost',
                 'host_neighbourhood',
                 'host_listings_count',
                 'host_total_listings_count',
                 'host_verifications',
                 'host_has_profile_pic',
                 'host_identity_verified',
                 'neighbourhood',
                 'neighbourhood_cleansed',
                 'latitude',
                 'longitude',
                 'property_type',
                 'room_type',
                 'accommodates',
                 'bathrooms',
                 'bedrooms',
                 'beds',
                 'amenities',
                 'price',
                 'minimum_nights',
                    'maximum_nights',
                    'has_availability',
                    'availability_30',
                    'availability_60',
                    'availability_90',
                    'availability_365',
                    'calendar_last_scraped',
                    'number_of_reviews',
                    'number_of_reviews_ltm',
                    'number_of_reviews_l30d',
                    'first_review',
                    'last_review',
                    'review_scores_rating',
                    'review_scores_accuracy',
                    'review_scores_cleanliness',
                    'review_scores_checkin',
                    'review_scores_communication',
                    'review_scores_location',
                    'review_scores_value',
                    'instant_bookable',
                    'calculated_host_listings_count',
                    'calculated_host_listings_count_entire_homes',
                    'calculated_host_listings_count_private_rooms',
                    'calculated_host_listings_count_shared_rooms',
                    'reviews_per_month'
                 ]

df_listings = df_listings[saved_columns]

In [36]:
df_listings.head()

,id,last_scraped,name,description,neighborhood_overview,host_id,host_name,host_location,host_about,host_response_time,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,13913,2025-09-16,Holiday London DB Room Let-on going,My bright double bedroom with a large window h...,Finsbury Park is a friendly melting pot commun...,54730,Alina,"London, United Kingdom",I am a Multi-Media Visual Artist and Creative ...,within a few hours,...,4.81,4.87,4.78,4.78,f,2,1,1,0,0.30
1,15400,2025-09-16,Bright Chelsea Apartment. Chelsea!,Lots of windows and light. St Luke's Gardens ...,It is Chelsea.,60302,Philippa,"Royal Borough of Kensington and Chelsea, Unite...","English, grandmother, I have travelled quite ...",NaN,...,4.88,4.84,4.93,4.74,f,1,1,0,0,0.51
2,17402,2025-09-16,Very Central Modern 3-Bed/2 Bath By Oxford St W1,"You'll have a great time in this beautiful, cl...","Fitzrovia is a very desirable trendy, arty and...",67564,Liz,"London, United Kingdom",We are Liz and Jack. We manage a number of ho...,within an hour,...,4.72,4.72,4.89,4.61,f,2,2,0,0,0.32
3,24328,2025-09-18,Battersea live/work artist house,"Artist house by SW Battersea Park, bright high...","- Battersea is a quiet family area, easy acces...",41759,Joe,"London, United Kingdom","I've been using Airbnb for a while now, both a...",within a few hours,...,4.90,4.93,4.60,4.65,f,1,1,0,0,0.53
4,36274,2025-09-15,Bright 1 bedroom apt off brick lane in Shoreditch,*Update June '25- Pump Installed to improve wa...,NaN,133271,Hendryks,"London, United Kingdom","We are Hendryks Services - your resident, mana...",within an hour,...,4.62,4.46,4.85,4.54,t,2,2,0,0,0.09

## Police

### UK

In [2]:
df_police_uk = pd.read_csv(r"C:\Users\jancw\Desktop\Studia\Sem 7\BigData\Projekt\data\police_london\2025-06\2025-06-city-of-london-street.csv")

In [35]:
df_police_uk.head(10)

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,eb3f73b6c12ed43a5d6f21a6c67db483d68ad72cbc9dbf...,2025-06,City of London Police,City of London Police,-1.459513,53.033956,On or near Thornton Way,E01019412,Amber Valley 009C,Other crime,Offender given a caution,NaN
1,b7b4cd09a21e8464ad4357703e6d15f85a34916e95ff47...,2025-06,City of London Police,City of London Police,0.124694,51.397466,On or near Barnfield Road,E01000728,Bromley 019E,Drugs,Under investigation,NaN
2,a622857087db4dd9ecacac944d0d6f45f047bdaec2a93a...,2025-06,City of London Police,City of London Police,-0.107682,51.517786,On or near B521,E01000917,Camden 027C,Criminal damage and arson,Under investigation,NaN
3,d63d1a68befe3f40d8e30c0231cc6b295050df206bc832...,2025-06,City of London Police,City of London Police,-0.107682,51.517786,On or near B521,E01000917,Camden 027C,Theft from the person,Under investigation,NaN
4,8adc8e773f86dfd13ad90506a772f088c684966bab4ef9...,2025-06,City of London Police,City of London Police,-0.112096,51.515942,On or near Nightclub,E01000914,Camden 028B,Burglary,Under investigation,NaN
5,6a486a9ad42a8fea7310ad2f0a43ec4688af2328c515bf...,2025-06,City of London Police,City of London Police,-0.111596,51.518281,On or near Chancery Lane,E01000914,Camden 028B,Other theft,Under investigation,NaN
6,9e91b42a5105e30cdabd77bd90510d3713c51a8f136aa6...,2025-06,City of London Police,City of London Police,-0.097078,51.519045,On or near A1,E01000001,City of London 001A,Bicycle theft,Under investigation,NaN
7,c61e24d09d3c4ef73ca4f667321c11ddceb83167f6a25a...,2025-06,City of London Police,City of London Police,-0.096718,51.515511,On or near Conference/Exhibition Centre,E01000001,City of London 001A,Burglary,Under investigation,NaN
8,faa5f901b4fd23b591d06089098d9140fabfb35164fcec...,2025-06,City of London Police,City of London Police,-0.097078,51.519045,On or near A1,E01000001,City of London 001A,Criminal damage and arson,Under investigation,NaN
9,0e0d940e039e3ece19666ce15a35ee394be84835841529...,2025-06,City of London Police,City of London Police,-0.098519,51.517332,On or near Little Britain,E01000001,City of London 001A,Other theft,Investigation complete; no suspect identified,NaN

In [ ]:
df_police_uk.info() 
drop = ['context']

# null columns in df_police_uk: (possibly more) Longitude, Latitude, LSOA code, LSOA name, Last outcome category

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 701 entries, 0 to 700
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Crime ID               693 non-null    object
 1   Month                  701 non-null    object
 2   Reported by            701 non-null    object
 3   Falls within           701 non-null    object
 4   Longitude              666 non-null    float64
 5   Latitude               666 non-null    float64
 6   Location               701 non-null    object
 7   LSOA code              666 non-null    object
 8   LSOA name              666 non-null    object
 9   Crime type             701 non-null    object
 10  Last outcome category  693 non-null    object
 11  Context                0 non-null      float64
dtypes: float64(3), object(9)
memory usage: 65.8+ KB

### NYPD

In [4]:
df_police_nyc = pd.read_csv(r"C:\Users\jancw\Desktop\Studia\Sem 7\BigData\Projekt\data\NYPD_Arrest_Data_(Year_to_Date)_20251206.csv")

In [8]:
df_police_nyc['AGE_GROUP'].unique()

array(['(null)', '25-44', '18-24', '45-64', '<18', '65+'], dtype=object)

In [4]:
df_police_nyc.head()

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Location
0,298760433,01/02/2025,782,"WEAPONS, POSSESSION, ETC",236.0,DANGEROUS WEAPONS,PL 2650101,M,Q,115,3,(null),(null),BLACK,0,0,0.000000,0.000000,POINT (0 0)
1,299030225,01/07/2025,105,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,F,M,28,0,25-44,M,BLACK,997439,233857,40.808558,-73.952357,POINT (-73.952357 40.808558)
2,299127494,01/08/2025,849,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,LOC00000V0,V,K,81,1,(null),(null),WHITE,0,0,0.000000,0.000000,POINT (0 0)
3,299188536,01/09/2025,259,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",351.0,CRIMINAL MISCHIEF & RELATED OF,PL 1450001,M,M,7,2,(null),(null),BLACK,0,0,0.000000,0.000000,POINT (0 0)
4,299533742,01/16/2025,155,RAPE 2,104.0,RAPE,PL 1303001,F,K,81,0,18-24,F,BLACK,1005319,190473,40.689464,-73.924029,POINT (-73.9240290899499 40.6894642952604)

In [5]:
(df_police_nyc['Latitude']==0.0).sum()

431

In [ ]:
df_police_nyc.info()
# null columns in df_police_nyc: KY_CD, LAW_CAT_CD
# null as string "(null)" in PD_DESC, OFNS_DESC, AGE_GROUP, PERP_SEX
# 0.0 in LATITUDE, LONGITUDE
# drop = ['LOCATION','LAW_CODE'] ? Y_COORD_CD, X_COORD_CD
# MAP = ['LAW_CAT_CD','ARREST_BORO','JURISDICTION_CODE','PREP_SEX',]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212486 entries, 0 to 212485
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ARREST_KEY         212486 non-null  int64
 1   ARREST_DATE        212486 non-null  object
 2   PD_CD              212486 non-null  int64
 3   PD_DESC            212486 non-null  object
 4   KY_CD              212470 non-null  float64
 5   OFNS_DESC          212486 non-null  object
 6   LAW_CODE           212486 non-null  object
 7   LAW_CAT_CD         211482 non-null  object
 8   ARREST_BORO        212486 non-null  object
 9   ARREST_PRECINCT    212486 non-null  int64
 10  JURISDICTION_CODE  212486 non-null  int64
 11  AGE_GROUP          212486 non-null  object
 12  PERP_SEX           212486 non-null  object
 13  PERP_RACE          212486 non-null  object
 14  X_COORD_CD         212486 non-null  int64
 15  Y_COORD_CD         212486 non-null  int64
 16  Latitude           212486 non-null  float64
 17  Longitude          212486 non-null  float64
 18  Location           212486 non-null  object
dtypes: float64(3), int64(6), object(10)
memory usage: 30.8+ MB

In [4]:
# show all columns where (null) appears at least once
for col in df_police_nyc.columns:
    if df_police_nyc[col].astype(str).str.contains('\(null\)').any():
        print(col)

<>:3: SyntaxWarning: invalid escape sequence '\('
<>:3: SyntaxWarning: invalid escape sequence '\('
C:\Users\jancw\AppData\Local\Temp\ipykernel_4836\2042188353.py:3: SyntaxWarning: invalid escape sequence '\('
  if df_police_nyc[col].astype(str).str.contains('\(null\)').any():

PD_DESC
OFNS_DESC
AGE_GROUP
PERP_SEX